# Generated by Django 2.1.2 on 2018-10-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabber', '0002_auto_20181022_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='comment',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
