# Generated by Django 2.1.2 on 2018-10-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('value', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='', max_length=50)),
                ('sender_password', models.CharField(default='', max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(default='', max_length=10)),
                ('subject', models.CharField(default='', max_length=50)),
                ('body', models.TextField(default='')),
                ('country', models.CharField(default='unknown', max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
                ('method', models.CharField(default='', max_length=1)),
                ('by_virus', models.CharField(default='', max_length=1)),
                ('by_fishing', models.CharField(default='', max_length=1)),
                ('date_add', models.CharField(default='', max_length=20)),
                ('date_hacked', models.CharField(default='', max_length=20)),
                ('priority', models.CharField(default='', max_length=20)),
                ('comment', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='0', max_length=1)),
                ('who_hacked', models.CharField(default='', max_length=20)),
                ('deleted', models.CharField(default='', max_length=1)),
                ('who_delete', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
